src/Entity/Article.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiProperty;
use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;

#[ApiResource]
#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $libelle_court = null;

    #[ORM\Column(length: 100)]
    private ?string $libelle = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: "decimal", precision: 15, scale: 2)]
    private ?string $prix_HT = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?SousRubrique $sous_rubrique = null;

    /**
     * @var Collection<int, Fournit>
     */
    #[ORM\OneToMany(targetEntity: Fournit::class, mappedBy: 'id_article')]
    private Collection $fournits;

    /**
     * @var Collection<int, ComposerDe>
     */
    #[ORM\OneToMany(targetEntity: ComposerDe::class, mappedBy: 'id_article')]
    private Collection $composerDes;

    /**
     * @var Collection<int, LivraisonArticle>
     */
    #[ORM\OneToMany(targetEntity: LivraisonArticle::class, mappedBy: 'id_article')]
    private Collection $livraisonArticles;

    /**
     * @var Collection<int, Gere>
     */
    #[ORM\OneToMany(targetEntity: Gere::class, mappedBy: 'article')]
    private Collection $geres;

    public function __construct()
    {
        $this->fournits = new ArrayCollection();
        $this->composerDes = new ArrayCollection();
        $this->livraisonArticles = new ArrayCollection();
        $this->geres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelleCourt(): ?string
    {
        return $this->libelle_court;
    }

    public function setLibelleCourt(string $libelle_court): static
    {
        $this->libelle_court = $libelle_court;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getPrixHT(): ?string
    {
        return $this->prix_HT;
    }

    public function setPrixHT(string $prix_HT): static
    {
        $this->prix_HT = $prix_HT;

        return $this;
    }

    public function getSousRubrique(): ?SousRubrique
    {
        return $this->sous_rubrique;
    }

    public function setSousRubrique(?SousRubrique $sous_rubrique): static
    {
        $this->sous_rubrique = $sous_rubrique;

        return $this;
    }

    /**
     * @return Collection<int, Fournit>
     */
    public function getFournits(): Collection
    {
        return $this->fournits;
    }

    public function addFournit(Fournit $fournit): static
    {
        if (!$this->fournits->contains($fournit)) {
            $this->fournits->add($fournit);
            $fournit->setIdArticle($this);
        }

        return $this;
    }

    public function removeFournit(Fournit $fournit): static
    {
        if ($this->fournits->removeElement($fournit)) {
            // set the owning side to null (unless already changed)
            if ($fournit->getIdArticle() === $this) {
                $fournit->setIdArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ComposerDe>
     */
    public function getComposerDes(): Collection
    {
        return $this->composerDes;
    }

    public function addComposerDe(ComposerDe $composerDe): static
    {
        if (!$this->composerDes->contains($composerDe)) {
            $this->composerDes->add($composerDe);
            $composerDe->setIdArticle($this);
        }

        return $this;
    }

    public function removeComposerDe(ComposerDe $composerDe): static
    {
        if ($this->composerDes->removeElement($composerDe)) {
            // set the owning side to null (unless already changed)
            if ($composerDe->getIdArticle() === $this) {
                $composerDe->setIdArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, LivraisonArticle>
     */
    public function getLivraisonArticles(): Collection
    {
        return $this->livraisonArticles;
    }

    public function addLivraisonArticle(LivraisonArticle $livraisonArticle): static
    {
        if (!$this->livraisonArticles->contains($livraisonArticle)) {
            $this->livraisonArticles->add($livraisonArticle);
            $livraisonArticle->setIdArticle($this);
        }

        return $this;
    }

    public function removeLivraisonArticle(LivraisonArticle $livraisonArticle): static
    {
        if ($this->livraisonArticles->removeElement($livraisonArticle)) {
            // set the owning side to null (unless already changed)
            if ($livraisonArticle->getIdArticle() === $this) {
                $livraisonArticle->setIdArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Gere>
     */
    public function getGeres(): Collection
    {
        return $this->geres;
    }

    public function addGere(Gere $gere): static
    {
        if (!$this->geres->contains($gere)) {
            $this->geres->add($gere);
            $gere->setArticle($this);
        }

        return $this;
    }

    public function removeGere(Gere $gere): static
    {
        if ($this->geres->removeElement($gere)) {
            // set the owning side to null (unless already changed)
            if ($gere->getArticle() === $this) {
                $gere->setArticle(null);
            }
        }

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\SousRubrique;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle_court')
            ->add('libelle')
            ->add('image')
            ->add('prix_HT')
            ->add('sous_rubrique', EntityType::class, [
                'class' => SousRubrique::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/article')]
class ArticleController extends AbstractController
{
    #[Route('/', name: 'app_article_index', methods: ['GET'])]
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_article_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_show', methods: ['GET'])]
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_article_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_delete', methods: ['POST'])]
    public function delete(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('app_article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <h1>Edit Article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
    <a href="{{ path('app_accueil') }}">acceuil</a>
    <h1>Article index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Libelle_court</th>
                <th>Libelle</th>
                <th>Image</th>
                <th>Prix_HT</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.libelleCourt }}</td>
                <td>{{ article.libelle }}</td>
                <td>{{ article.image }}</td>
                <td>{{ article.prixHT }}</td>
                <td>
                    <a href="{{ path('app_article_show', {'id': article.id}) }}">show</a>
                    <a href="{{ path('app_article_edit', {'id': article.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_article_new') }}">Create new</a>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <h1>Create new Article</h1>

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('app_article_index') }}">back to list</a>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h1>Article</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Libelle_court</th>
                <td>{{ article.libelleCourt }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ article.libelle }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ article.image }}</td>
            </tr>
            <tr>
                <th>Prix_HT</th>
                <td>{{ article.prixHT }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_article_index') }}">back to list</a>

    <a href="{{ path('app_article_edit', {'id': article.id}) }}">edit</a>


    {{ include('article/_delete_form.html.twig') }}
{% endblock %}